# Generated by Django 6.0.3 on 2026-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_year', models.IntegerField(verbose_name="Tug'ilga yili")),
                ('address', models.TextField(verbose_name='Yashash manzili')),
            ],
        ),
    ]
