# Generated by Django 6.0.3 on 2026-04-05 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Faqat o'zbekiston aloqa operatorlaridan foydalanib ro'yxatdan o'tish mumkin.", regex='^\\+?998\\s?(33|77|88|90|91|93|94|95|97|98|99|71|66)[0-9]{7}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
