# Generated by Django 6.0.4 on 2026-04-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='ammount',
            new_name='amount',
        ),
    ]
