# Generated by Django 6.0.3 on 2026-03-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='ism')),
                ('age', models.IntegerField()),
                ('phone_num', models.CharField(max_length=155)),
            ],
        ),
    ]
