worker_processes 1;
error_log /Users/xazratbek/programming/najot-talim/django-rest-framework/QuranAPI/deploy/local/logs/nginx-error.log;
pid /Users/xazratbek/programming/najot-talim/django-rest-framework/QuranAPI/deploy/local/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /Users/xazratbek/programming/najot-talim/django-rest-framework/QuranAPI/deploy/local/logs/nginx-access.log;
    sendfile on;

    upstream quranapi_local {
        server unix:/tmp/quranapi-run/gunicorn.sock fail_timeout=0;
    }

    server {
        listen 8088;
        server_name localhost;

        client_max_body_size 10M;

        location /static/ {
            alias /Users/xazratbek/programming/najot-talim/django-rest-framework/QuranAPI/staticfiles/;
        }

        location / {
            proxy_pass http://quranapi_local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
