[unix_http_server]
file=/tmp/quranapi-run/supervisor.sock

[supervisord]
logfile=%(here)s/logs/supervisord.log
pidfile=/tmp/quranapi-run/supervisord.pid
childlogdir=%(here)s/logs
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/quranapi-run/supervisor.sock

[program:quranapi]
directory=/Users/xazratbek/programming/najot-talim/django-rest-framework/QuranAPI
command=/Library/Frameworks/Python.framework/Versions/3.14/bin/python3 -m gunicorn config.wsgi:application -c deploy/local/gunicorn.local.conf.py
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=%(here)s/logs/supervisor-quranapi.log
