"""add users table

Revision ID: 3168f3ed356d
Revises: cf50741c93c6
Create Date: 2026-07-02 11:12:32.433811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3168f3ed356d'
down_revision: Union[str, None] = 'cf50741c93c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('comments', 'user',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('saveds', 'user',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saveds', 'user',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.alter_column('comments', 'user',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
