from django.urls import path

from .views import (
    CategoryCreateView,
    CategoryDeleteView,
    CategoryDetailView,
    CategoryListView,
    CategoryUpdateView,
    OrderCreateView,
    OrderDeleteView,
    OrderDetailView,
    OrderItemCreateView,
    OrderItemDeleteView,
    OrderItemDetailView,
    OrderItemListView,
    OrderItemUpdateView,
    OrderListView,
    OrderUpdateView,
    TelefonCreateView,
    TelefonDeleteView,
    TelefonDetailView,
    TelefonListView,
    TelefonUpdateView,
)

urlpatterns = [
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
    path("categories/create/", CategoryCreateView.as_view(), name="category_create"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category_detail"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="category_update"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category_delete"),
    path("", TelefonListView.as_view(), name="telefon_list"),
    path("telefonlar/create/", TelefonCreateView.as_view(), name="telefon_create"),
    path("telefonlar/<int:pk>/", TelefonDetailView.as_view(), name="telefon_detail"),
    path("telefonlar/<int:pk>/update/", TelefonUpdateView.as_view(), name="telefon_update"),
    path("telefonlar/<int:pk>/delete/", TelefonDeleteView.as_view(), name="telefon_delete"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("order-items/", OrderItemListView.as_view(), name="orderitem_list"),
    path("order-items/create/", OrderItemCreateView.as_view(), name="orderitem_create"),
    path("order-items/<int:pk>/", OrderItemDetailView.as_view(), name="orderitem_detail"),
    path("order-items/<int:pk>/update/", OrderItemUpdateView.as_view(), name="orderitem_update"),
    path("order-items/<int:pk>/delete/", OrderItemDeleteView.as_view(), name="orderitem_delete"),
]
