# Generated by Django 6.0.3 on 2026-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(blank=True, max_length=255)),
                ('ram', models.PositiveIntegerField(help_text='GB')),
                ('storage', models.PositiveIntegerField(help_text='GB')),
                ('storage_type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=50)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resolution', models.CharField(max_length=50)),
                ('battery', models.PositiveIntegerField(blank=True, help_text='mAh', null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('os', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
