# Generated by Django 6.0.3 on 2026-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='laptop/%Y/%M/%d/'),
        ),
    ]
