# Generated by Django 6.0.5 on 2026-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0007_alter_ayah_audio_alter_ayah_audio_secondary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayah',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='juz',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='surah',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='ayah',
            name='sajda_obligatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ayah',
            name='sajda_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ayah',
            name='sajda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edition',
            name='identifier',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='surah',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ayah',
            unique_together={('surah', 'edition', 'number_in_surah')},
        ),
        migrations.AlterUniqueTogether(
            name='juz',
            unique_together={('number', 'edition')},
        ),
    ]
