# Generated by Django 6.0.5 on 2026-07-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qurancloud', '0008_alter_ayah_options_alter_juz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['identifier']},
        ),
    ]
