# Generated by Django 6.0.4 on 2026-04-17 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_promocode_alter_productview_product_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('public', 'Public'), ('personal', 'Personal')], default='welcome', max_length=30),
        ),
        migrations.AddField(
            model_name='promocode',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text="Promo code turi masalan: Birinchi xarid uchun 30 000 so'm sovg'a", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='last_used_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
