# Generated by Django 5.2.16 on 2026-07-09 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Booking link: /b/<slug>/", max_length=80, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Ushbu biznesning o'z Telegram boti tokeni (BotFather).",
                        max_length=200,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("start", "Start — 150,000 UZS/oy"),
                            ("pro", "Pro — 300,000 UZS/oy"),
                        ],
                        default="start",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("position", models.CharField(blank=True, max_length=100)),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        help_text="Yangi bandlar haqida xabar oladigan Telegram chat ID.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
