# Generated by Django 6.0.3 on 2026-04-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_nomi', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('yonalish', models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('mobile', 'MOBILE')], default='backend', max_length=50)),
                ('boshlanish_sanasi', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash_sanasi', models.DateField(verbose_name='Tugash sanasi')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'guruh',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(help_text='Familiyani kiriting', max_length=100, verbose_name='Familiya')),
                ('yosh', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studentlar',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('familiya', models.CharField(max_length=150)),
                ('yonalish', models.CharField(choices=[('backend', 'BACKEND'), ('frontend', 'FRONTEND'), ('mobile', 'MOBILE')], default='backend', max_length=150)),
                ('staj', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacherlar',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.student')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='erp.teacher'),
        ),
    ]
