# Generated by Django 6.0.3 on 2026-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=29)),
                ('make', models.CharField(choices=[('bmw', 'BMW'), ('audi', 'AUDI'), ('mers', 'MERS'), ('chevrolet', 'Chevrolet')], default='bmw', max_length=29)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(upload_to='cars/')),
                ('year', models.PositiveIntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'db_table': 'cars',
                'ordering': ['-id'],
            },
        ),
    ]
